# Generated by Django 5.0.4 on 2024-04-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_score',
            field=models.IntegerField(default=0),
        ),
    ]
