# Generated by Django 5.0.4 on 2024-04-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_subject_subject_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_score',
            field=models.IntegerField(null=True),
        ),
    ]
