# Generated by Django 5.0.4 on 2024-04-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_summary_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='answer_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
